CC=g++
CFLAGS=-std=c++11
INCDIRS=-I.
LIBDIRS=
LIBS=-lSDL2 -lGLEW -lGL
SOURCES=main.cpp Shader.cpp Attribute.cpp
TARGET=main
all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET) $(INCDIRS) $(LIBDIRS) $(LIBS)

